#!/bin/bash

REMOVED="
Editor.StrokeSelectMode.js"

LIST="
Classifier.js
Editor.EditorMode.js
Editor.DrawMode.js
Editor.SelectionMode.js
Editor.RectSelectMode.js
Editor.js
Editor.PermEvents.js
Editor.Events.js
Editor.Buttons.js
Editor.Constants.js
CorrectionMenu.js
CorrectionMenu.SymbolTree.js
RenderManager.js
CollisionManager.js
RecognitionManager.js
BoundingBox.js
Segment.js
PenStroke.js
ImageBlob.js
SymbolSegment.js
SegmentGroup.js
Action.js
Action.CompositeAction.js
Action.AddSegments.js
Action.TransformSegments.js
Action.GroupSegments.js
Action.EditText.js
Action.DeleteSegments.js
Action.Undo.js
Action.Redo.js
Utils.js
TeX_Input.js
third_party/iosSlider/jquery.easing-1.3.js
third_party/iosSlider/jquery.iosslider.js
Slider.js"
	

# Concatenate files in the given order.
cat $LIST > 00_AllJS.js

cd third_party
./genAllJS


